teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 0.5
      -
        axis: 6
        target: linear.y
        scale: 1.0
      -
        axis: 7
        target: linear.z
        scale: 1.0

  start_controller:
    type: service
    service_name: /start_controller
    service_request: ""
    buttons: [7]

  record:
    type: service
    service_name: /record
    service_request: ""
    buttons: [1]

  play:
    type: service
    service_name: /play
    service_request: ""
    buttons: [2]

  start_eval:
    type: service
    service_name: /start_eval
    service_request: ""
    buttons: [0]

  stop_eval:
    type: service
    service_name: /stop_eval
    service_request: ""
    buttons: [3]
