teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 0.5
      -
        axis: 6
        target: linear.y
        scale: 1.0
      -
        axis: 7
        target: linear.z
        scale: 1.0
